// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6ZOKzTwcQeFQx6iDyW3QOrTVSqd5Y_c',
    appId: '1:241097813370:web:3044018fab69250ffc3ac3',
    messagingSenderId: '241097813370',
    projectId: 'easyshop-983ad',
    authDomain: 'easyshop-983ad.firebaseapp.com',
    storageBucket: 'easyshop-983ad.firebasestorage.app',
    measurementId: 'G-2SZYBPSV1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_dOsUnEj9kgbvGFgrPxvfPnx36lp1P0',
    appId: '1:241097813370:android:91e350ae79c9ed46fc3ac3',
    messagingSenderId: '241097813370',
    projectId: 'easyshop-983ad',
    storageBucket: 'easyshop-983ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZGW_j0QmZPrbgrjgf0e8tYuBgJxdcWOw',
    appId: '1:241097813370:ios:7417ede197b77a90fc3ac3',
    messagingSenderId: '241097813370',
    projectId: 'easyshop-983ad',
    storageBucket: 'easyshop-983ad.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZGW_j0QmZPrbgrjgf0e8tYuBgJxdcWOw',
    appId: '1:241097813370:ios:7417ede197b77a90fc3ac3',
    messagingSenderId: '241097813370',
    projectId: 'easyshop-983ad',
    storageBucket: 'easyshop-983ad.firebasestorage.app',
    iosBundleId: 'com.example.easyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy6ZOKzTwcQeFQx6iDyW3QOrTVSqd5Y_c',
    appId: '1:241097813370:web:24baba71d449271bfc3ac3',
    messagingSenderId: '241097813370',
    projectId: 'easyshop-983ad',
    authDomain: 'easyshop-983ad.firebaseapp.com',
    storageBucket: 'easyshop-983ad.firebasestorage.app',
    measurementId: 'G-X2ZJ8YV1CB',
  );
}
